<?php


?>


<?php include _X_LAYOUT . '/sitemin/include_vue.phtml'; ?>

<script>
var _token='<?=$rs['_token'];?>';
</script>

<div class="container-fluid" id="sixthTable">

	<div class="container">
		
			<h3 class="text-uppercase mt-5">Module Control</h3>
			<table class="table table-striped table-hover">
				<tr>
					<th v-on:click="sortTable('name')">[name]
						<div class="arrow"  v-if=" 'name' == sortColumn" v-bind:class="[ascending ? 'arrow_up' : 'arrow_down']"></div>
					</th>
					<th>path</th>
					<th>status</th>
				</tr>
				<tr v-for="row in get_rows()" >
				    <td valign="top" v-for="col in columns" :class="'v-'+col">
					<a v-if="row[col] == 'YES' || row[col] == 'NO'" href="#" v-on:click="status(row['path'],row[col])">{{row[col]}}</a>
					<span v-else>{{row[col]}}</span>
				    </td>
				</tr>
			</table>
			
			<script>
			var sixthTable = new Vue({
				el: '#sixthTable',
				data: {
					currentPage: 1,
					elementsPerPage: 102,
					ascending: false,
					sortColumn: '',
					rows :  $.ajax({
							url: '?cmd=list&_token='+_token,
							method: 'POST',
							dataType: 'json',
							async: false
						}).responseJSON || []
					},
				methods: {
					"sortTable": function (col) {
							if (this.sortColumn === col) {
								this.ascending = !this.ascending;
							} else {
								this.ascending = true;
								this.sortColumn = col;
							}

							var ascending = this.ascending;

							this.rows.sort(function(a, b) {
								if (a[col] > b[col]) {
									return ascending ? 1 : -1
								} else if (a[col] < b[col]) {
									return ascending ? -1 : 1
								}
								return 0;
							})
						},
					"get_rows": function () {
							//if(!this.rows || this.rows.length == 0 ) return []
							var start = (this.currentPage-1) * this.elementsPerPage;
							var end = start + this.elementsPerPage;
							return this.rows.slice(start, end);
						},
					"status" : function(p, s){
						if(!confirm( (s=='YES' ? "Disable Module:":"Enabled Module")+ p) ) return;
						common.mask.up()
						$.ajax({
						  url: '?cmd=status&p='+p+'&s='+s+'&_token='+_token,
						  success: function(data){
							window.location.reload();
							//common.mask.down()
						  }
						});
					}
				},
				computed: {
					"columns": function columns() {
						if (this.rows.length == 0) return [];
						return Object.keys(this.rows[0])
					}
				}
			});

			</script>
		
	</div>
    
</div>
<hr>