<!DOCTYPE html>
<html lang="en">
<head>
	<title><?=$page_title;?></title>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<meta name="robots" content="noindex"><!-- not for admin -->
	<meta property="og:image" content="/media/image/admin.jpg" />

	<link href="/media/image/micon.png" rel="shortcut icon">

	<script src="/package/jquery/jquery.js"></script>
	<!-- <script src="/js/tether.min.js"></script> -->

	<link rel="stylesheet" href="/package/jquery-ui-1.11.4/themes/smoothness/jquery-ui.css">
	<script src="/package/jquery-ui-1.11.4/jquery-ui.js"></script>


	<script src="/package/bootstrap4/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="/package/bootstrap4/css/bootstrap.min.css">

	<link rel="stylesheet" href="/package/font-awesome-4.7.0/css/font-awesome.css">

	<link rel="stylesheet" href="/package/common/common.css">
	<script src="/package/common/common.js"></script>

</head>
<body id="page-top" class="admin <?=$page_name?>" >
