<?php
?>

<div class="container">
		<div class="title">
			<h3 class="mt-4 textAlignCenter">SITEMIN INSTALLATION</h3>
		</div>
	
	
		 <!-- file permission-->
		 <div class="form-group">
			 <!-- file permission-->
			 <div class="permission"> </div>
			 <div class="clear"></div>
			 <!-- retry -->
			 <span class="floatRight"> Please change the permission  by "chmod", and  <button type="button" id="re-test-file" class="none btn btn-danger " onclick="window.location.reload()"> Test again</button></span>
		 </div>
		 <div class="clear"></div>


		 <!-- database credential-->
		 <form action="/action_page.php">
			<div class="form-group">
				<label for="host">Database Server Host Name ot IP:</label>
				<input type="text" class="form-control" placeholder="Enter database host name or IP " id="host" required>
			</div>
			<div class="form-group">
				<label for="database">Database Name:</label>
				<input type="text" class="form-control" placeholder="database name" id="database">
			</div>
			<div class="form-group">
				<label for="user">Database User:</label>
				<input type="text" class="form-control" placeholder="database user" id="user">
			</div>
			<div class="form-group">
				<label for="password">Database User Password:</label>
				<input type="password" class="form-control" placeholder="database user password" id="password">
			</div>
						 <!-- retry -->
						 <span class="floatRight"> after fill in above database items <button type="button" id="re-test-file" class="none btn btn-danger " onclick="window.location.reload()"> Test Connection</button></span>
		</form> 
		<div class="clear"></div>

</div>

<script>
(function($){
	$.ajax({
//	        url: "#",
	        dataType:'json',
	        data:{step:'file permission'},
		success: function(ret){
			if(ret.data.ok)
				ret.data.ok.forEach(function(v, i){
					$('.permission').append('<div class="alert alert-success wp100"><strong><i class="fa fa-check-square" aria-hidden="true"></i></strong> ' + v + ' <span class="badge badge-success">Check\'s OK</span></div>')
				})
			if(ret.data.failed){
				ret.data.failed.forEach(function(v, i){
					$('.permission').append('<div class="alert alert-warning wp100"><strong><i class="fa fa-window-close" aria-hidden="true"></i></strong> ' + v + ' <span class="badge badge-warning">Check\'s failed</span></div>')
				})

				$('.re-test-file').show();


			}


		}
	});


})(jQuery)



function reset_my_password(){
    common.mask.up("Sending request to your email");
    $.ajax({
        url: '/sitemin/requestpassword',
        data: {email:$('#rsemail').val()},
        success: function(data){
            common.mask.down();
            $("#myModal").modal('hide')
            $('.login-page').html('<h3>Reset Password link has been sent to your email</h3><h4>Please follow the link in the email to reset your password!</h4><button onclick="window.location.reload()">Try Login</button>')
        }
    });
}


function ajax_login(form){
	common.mask.up()
	//$('.alert').attr('class', 'alert').html('<img src="<?=_X_URL?>/media/image/ajax-loader.gif" />');
	$.ajax({
        url: "/sitemin/loginajax",
        dataType:'json',
        data:$(form).serialize(),
        type:'post',

		success: function(ret){
//			$('.vcode-image').click();
//			$('.vcode-input').val('');
			if(ret && ret.status == 'ok'){
				//insert multiple login
				/*
				if(ret.msg_type){
					$('#rusername').val(ret.msg_type);
					$('#rpassword').val($('.password-input').val());
					for(var k in ret.msg){
						var fn = 'riframe'+Math.random();
						//create iframe and h
						$('body').append('<iframe  class="visibilityHidden" id="'+fn+'"  name="'+fn+'" ></iframe>');
						$('#rform').attr('action', ret.msg[k].login_url);
						$('#rform').attr('target', fn);
						$('#rform').submit();
					}
				}
				*/
				window.location = $('#ret').val();
			}else{
				common.mask.down();
                $('.login-page').html('<h3>Login failed</h3><h4 class="alert-'+ret.msg_type+'">'+ret.msg+'</h4><button onclick="window.location.reload()">Try Again</button>')
			}
		}
	});
	return false;
}

</script>



<!-- The Modal -->
<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Request to Reset password</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <p><small>a link to reset password will send via your account email</small></p>
                <input type="email" name="rsemail" value="" id="rsemail" />
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" onclick="reset_my_password()">send Request</button>
            </div>
				
        </div>
    </div>
</div>
<style>
    .modal-dialog  {
        top:15%;
    }
</style>