<?php
?>

<div class="container">
		<div class="title">
			<h3 class="mt-4 textAlignCenter">SITEMIN INSTALLATION</h3>
		</div>


		 <!-- file permission-->
		 <div class="form-group file-permission">
			 <!-- file permission-->
			 <div class="permission"> </div>
			 <div class="clear"></div>
			 <!-- retry -->
			 <span class="floatRight re-test-file"> Please change the permission  by "chmod", "chown", and  <button type="button" id="re-test-file" class="none btn btn-danger " onclick="test_file_permission()"> Test again</button></span>
		 </div>
		 <div class="clear"></div>


		 <!-- database credential-->
		 <form action="?" id="db-form" method="post">
		 	<div class="form-items">
			 	<input type="hidden" name="step" id="step" value="db connection" />
				<div class="form-group">
					<label for="host">Database Server Host Name ot IP:</label>
					<input type="text" class="form-control" placeholder="Enter database host name or IP " value="localhost" id="host" name="host" required>
				</div>
				<div class="form-group">
					<label for="database">Database Name:</label>
					<input type="text" class="form-control" placeholder="database name" id="database" value="mydatabase" name="database">
				</div>
				<div class="form-group">
					<label for="user">Database User:</label>
					<input type="text" class="form-control" placeholder="database user" id="user" value="myusername" name="user">
				</div>
				<div class="form-group">
					<label for="password">Database User Password:</label>
					<input type="password" class="form-control" placeholder="database user password" id="password" value="mypassword" name="password">
				</div>
					<!-- retry -->
					<span class="floatRight re-test-db"> after fill in above database items <button type="button"  class="none btn btn-danger " onclick="test_db_connection()"> Test Connection</button></span>

			</div>
			<div class="clear"></div>
			<div>&nbsp;</div>
			<pre class="msg p20 mt-20 Black Hide "></pre>
			<!-- to install after all checks ok -->
			<span class="floatRight Hide next" >
				All checks OK,
				 <br>to start installation click <button type="button"  onclick="install()" class="btn btn-info " >here</button>,
				 <br> it may take a few seconds,
				 <br>* and all data will be cleaned
			 </span>
		</form>
		<div class="clear"></div>
		<div class="form-group installed Hide">
			<div class="jumbotron alert alert-warning">
				<h1>Installation is done!</h1>
				<div class="clear"></div>
				<p class="fr"><b>click <a href="/sitemin/login">here</a> to login to admin</b></p>
				<div class="clear"></div>
				<p class="fr">Your Admin user is : "my" and the password is "123e456". After login please change it </p>
				<div class="clear"></div>
			</div>
			<div class="clear"></div>
		</div>
		<div class="clear"></div>
</div>

<script>

var checked = {file:0, db:0};

(function($){
	test_file_permission()
})(jQuery)



function install(){

	$('.file-permission').fadeOut();
	$('#db-form').fadeOut();
	$('#step').val("install")

	common.mask.up();
	$.ajax({
		dataType:'json',
		type:'post',
		data: $('#db-form').serialize(),
		success: function(ret){
			install_run()
		}
	});

}

function install_run(){
	//by calling one url to trigger the the setup script in sitemin
	$.ajax({
		url:"/sitemin/login",
		success: function(ret){
			common.mask.down();
			$('.installed').fadeIn();
		}
	});
}


function test_file_permission(){

	$('.permission').fadeOut().html("");
	$('.re-test-file').hide();
	common.mask.up();
	$.ajax({
        dataType:'json',
        data:{step:'file permission', a:Math.random()},
		type:'post',
		success: function(ret){
			if(ret.data.ok)
				ret.data.ok.forEach(function(v, i){
					$('.permission').append('<div class="alert alert-success wp100"><strong><i class="fa fa-check-square" aria-hidden="true"></i></strong> ' + v + ' <span class="badge badge-success">Check\'s OK</span></div>')
				})
			if(ret.data.failed){
				ret.data.failed.forEach(function(v, i){
					$('.permission').append('<div class="alert alert-warning wp100"><strong><i class="fa fa-window-close" aria-hidden="true"></i></strong> ' + v + ' <span class="badge badge-warning">Check\'s failed</span></div>')
				})
			}
			common.mask.down();
			$('.permission').fadeIn()
			if((ret.status == 'failed')){
				$('.re-test-file').show();
			}else{
				checked.file = 1;
			}
			to_install()
		}
	});

}


function test_db_connection(){
	$('.msg').fadeOut();
	$('.re-test-db').hide();
	common.mask.up();
	$.ajax({
        dataType:'json',
		type: 'post',
        data: $('#db-form').serialize(),
		success: function(ret){
			common.mask.down();
			if(ret && ret.status=='failed'){
				$('.msg').html(ret.data).fadeIn();
				$('.re-test-db').show();
			}else{
				checked.db = 1
				$('.form-items').fadeOut();
				$('.msg').html("Database connection checks ok").fadeIn();
			}
			to_install()
		}
	});

}


function to_install(){

	if(!checked.file || !checked.db) return;
	$('.next').show();

}

</script>
