<?php


?>


<?php include _X_LAYOUT . '/sitemin/include_vue.phtml'; ?>

<script>
var _token='<?=$rs['_token'];?>';
</script>

<div class="container-fluid" id="sixthTable">
	<!-- The Modal -->


	<div class="modal fade mt-7" id="myModal">
		<div class="modal-dialog modal-dialog-centered">
			<form id="modal_form" >
			<div class="modal-content">

				<!-- Modal Header -->
				<div class="modal-header pt-4">
					<h4 class="modal-title">Var</h4>
					<button type="button" class="close" data-dismiss="modal">&times;</button>
				</div>

				<!-- Modal body -->
				<div class="modal-body" id="edit_form">
						<input type="hidden" name="id" id="id" value="" />
						<div class="form-group">
							<label for="name">Name:</label>
							<input type="name" class="form-control" name="name" id="name">
						</div>
						<div class="form-group">
							<label for="value">Value:</label>
							<input type="value" class="form-control" name="value" id="value">
						</div>
                        <div class="form-group">
                            <label for="note">Note:</label>
                            <textarea name="note" id="note" cols="40" rows="6"></textarea>
                        </div>
				</div>

				<!-- Modal footer -->
				<div class="modal-footer">
					<button type="button" class="btn btn-warning" v-on:click="save_value()" >Submit</button>
				</div>

			</div>
			</form>
		</div>
	</div><!-- The Modal -->

	<div class="container">

			<h3 class="text-uppercase mt-5">System Vars</h3>
			<table class="table table-striped table-hover">
				<tr>
					<th v-on:click="sortTable('name')">[name]
						<div class="arrow"  v-if=" 'name' == sortColumn" v-bind:class="[ascending ? 'arrow_up' : 'arrow_down']"></div>
					</th>
					<th>value</th>
                    			<th>Note</th>
					<th v-on:click="sortTable('date')">[date]
						<div class="arrow"  v-if=" 'date' == sortColumn" v-bind:class="[ascending ? 'arrow_up' : 'arrow_down']"></div>
					</th>
                    <!-- <th>hour</th>
					<th>date</th>
					<th>month</th>
					<th>year</th>
					<th>weekday</th>
					<th v-on:click="sortTable('task')">task
						<div class="arrow"  v-if=" 'task' == sortColumn" v-bind:class="[ascending ? 'arrow_up' : 'arrow_down']"></div>
					</th>
					<th>next</th>
					<th>status</th> -->
					<th><button type="button" class="btn btn-extra-small btn-rounded btn-light-border" v-on:click="edit_cron(0, $event)"><span  class="fa fa-plus"></button></th>
				</tr>
				<tr v-for="row in get_rows()" >
					<td valign="top" v-for="col in columns" :class="'PRE v-'+col">{{row[col]}}</td>
					<td valign="top" class="">
						<a class="btn btn-extra-small btn-rounded btn-light-border" href="javascript:void(0);" v-on:click="edit_cron(row.name, $event)">
							<span  class="fa fafa fa-edit"> </span>
						</a>
						<!-- <a href="javascript:void(0);" v-on:click="status_toggle(row.id, $event)">
							<span v-if="row.status == 'active'" class="fa fa-pause"> Stop</span>
							<span  v-if="row.status == 'inactive'" class="fa fafa fa-play"> Active</span>
						</a> -->
					</td>
				</tr>
			</table>

			<script>
			var sixthTable = new Vue({
				el: '#sixthTable',
				data: {
					currentPage: 1,
					elementsPerPage: 102,
					ascending: false,
					sortColumn: '',
					rows :  $.ajax({
							url: '?cmd=list&_token='+_token,
							method: 'POST',
							dataType: 'json',
							async: false
						}).responseJSON || []
					},
				methods: {
					"sortTable": function (col) {
							if (this.sortColumn === col) {
								this.ascending = !this.ascending;
							} else {
								this.ascending = true;
								this.sortColumn = col;
							}

							var ascending = this.ascending;

							this.rows.sort(function(a, b) {
								if (a[col] > b[col]) {
									return ascending ? 1 : -1
								} else if (a[col] < b[col]) {
									return ascending ? -1 : 1
								}
								return 0;
							})
						},
					"get_rows": function () {
							//if(!this.rows || this.rows.length == 0 ) return []
							var start = (this.currentPage-1) * this.elementsPerPage;
							var end = start + this.elementsPerPage;
							return this.rows.slice(start, end);
						},
					"status_toggle" : function(id, ev){
						var e = ev.currentTarget;
						common.mask.up()
						$.ajax({
						  url: '?cmd=status_toggle&id='+id+'&_token='+_token,
						  success: function(data){
							window.location.reload();
							//common.mask.down()
						  }
						});
					},
					"edit_cron" : function(id, e){

						var tr = $(e.currentTarget).parent().parent();
						$('#name').val(tr.find('td:nth-child(1)').html()|| '')
						$('#value').val(tr.find('td:nth-child(2)').html()|| '')
						$('#note').val(tr.find('td:nth-child(3)').html()|| '')
						$("#myModal").modal('toggle')
					},
					"save_value": function(){
						common.mask.up()
						var form_data = $('#modal_form').serialize();
						$.ajax({
						  url: '?cmd=save&_token='+_token,
						  data: form_data,
						  success: function(data){
							window.location.reload();
							//common.mask.down()
						  }
						});
						$("#myModal").modal('toggle');
					}
				},
				computed: {
					"columns": function columns() {
						if (this.rows.length == 0) return [];
						return Object.keys(this.rows[0])
					}
				}
			});

			</script>

	</div>

</div>
<hr>
