<?php $page_title = $rs['TITLE']; ?>
<?php include _X_LAYOUT . '/sitemin/header.phtml'; ?>
<?php include _X_LAYOUT . '/sitemin/nav.phtml'; ?>
<!--  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">  -->
<!-- <link href="https://fonts.googleapis.com/css?family=Abel" rel="stylesheet">  -->
<div class="sitemin-content-wrapper ">
    <div class="container-fluid">


    	<?php
    		$path =  preg_match('/^\//', $rs['tpl']) ? _X_MODULE : '';
    		include $path . $rs['tpl'];
    	?>

    </div>
</div>

<?php include _X_LAYOUT . '/sitemin/footer.phtml'; ?>
