<?php
/**
 * perpare data
 */

//
//function treehtml($rs){
//	$con[] = "<ul>";
//	foreach ($rs as $k=>$v) {
//		$con[] = "<li>";
//		$con[] = "<span>{$v['display']}</span> &rarr; {$v['router']}";
//		if($v['children']){
//			$con[] = treehtml($v['children']);
//		}
//		$con[] = "</li>";
//	}
//	$con[] = "</ul>";
//	return implode("\n", $con);
//}

?>
    

<style>
.tree {
line-height:2.2em;
list-style-type:none;
}
/*
.tree li{
border-left:1px solid #333;
}*/
/** !!important: to on top of bootstrap modal's z-index:1050!!*/
.ui-front { z-index: 1060 !important;}

#div1 {
    width: 350px;
    height: 70px;
    padding: 10px;
    border: 1px solid #aaaaaa;
}
.menu-delete-grap {
margin-top:-24px !important;
}
.order-spacer{
height:3px;
}

.router{
overflow:scroll;
}
.modal-footer {border-top: none;}
</style>

<!--
<span><b>Root</b>&nbsp;</span>
<a href="javascript:void(0)" class="textDecorationNone" onclick="menu_control.new_menu_item(1)" >
	<i class="fa fa-plus-circle" aria-hidden="true"></i>
</a>
-->
<?php
//
//$arr = array(
//array(id=>a, o=>null),
//array(id=>b, o=>null),
//array(id=>c, o=>null),
//array(id=>d, o=>9),
//array(id=>e, o=>3),
//);
//
//_dv($arr);
//
//$brr = xpAS::sort_on($arr, 'o');
//_dv($brr, 1);

$template = <<<EOF

<div  class="menu-root" >
	<h4>Menu</h4>
	<ul class="menu-delete-grap  tree py-4"  >
		<!-- recursion start children -->
		<li id="m_{{id}}" >
			<div id="sort_{{parent_id}}_{{%K}}"  class="drop order-spacer" ondrop="order_save(event,this)" ondragover="order_area_show(event,this)" ondragleave="order_area_hide(this)"></div>

			<span style="float:left;">&#9492;  <!-- &#10662; &#9493;menu--></span>
			<span>&nbsp;</span>
			<a href="javascript:void(0)" class="textDecorationNone" onclick="$('#id').val(0);$('#new_id').val(0);$('#parent_id').val({{id}});$('#sitemin_menu_model').modal(); return false;" >
				<i class="fa fa-plus-square-o" aria-hidden="true" style="color:#269abc;"></i>
			</a>
			<a href="javascript:void(0)" class="textDecorationNone" onclick="if(!confirm('Are you sure you want to delete this node?')) return false; menu_item_delete({{id}})" >
				<i class="fa fa-minus-square-o" aria-hidden="true" style="color:#d58512;"></i>
			</a>
			<a id="edit_{{id}}" href="javascript:void(0)" class="textDecorationNone"
			onclick="$('#id').val({{id}});$('#new_id').val(0);$('#parent_id').val({{parent_id}});$('#display').val('{{display}}');$('#router').val('{{router}}'); $('#sitemin_menu_model').modal(); return false;" >
				<span><i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#4CAF50;"></i></span>
			</a>

			<span id="drag_{{id}}" draggable="true" ondragstart="drag(event, this)" class="Hand drop" ondrop="drop(event, this)" ondragover="allowDrop(event,this)" ondragleave="allowDrop_hide(this)" >
				<strong>&nbsp;{{display}}</strong>
				(#{{id}})
				(<i class="fa fa-user" aria-hidden="true" style="color:#bbb;"></i> {{role}})
				<i class="fa fa-arrow-circle-right" aria-hidden="true" style="color:#bbb;"></i> <a href="{{router}}" >{{router}}</a>
			</span>


			<ul id="s_{{id}}"  class="tree" >

				<!-- recursion children-->

			</ul>
			<div class="clear h0" ></div>
		</li>
		<!-- recursion end children -->
		<li class="last_li none clear"></li>
	</ul>
	<br class="clear" />
</div>
EOF;

$tpl = new xpTpl(array('string'=>$template));
$tpl->sets(array('children'=>$rs['data']));
$menutree_html = $tpl->html(false);

?>

   

<!-- grid table -->

<div class="contain-fluid">
    <div class="row">
        <div class="col-12 col-md-10 offset-md-1">    
            <div class="mt-5">
                    <div class="the-title">
                        <h3 class="text-uppercase">MENU<span class="small">- sitemin menu edit</span>  </h3>
                    </div>
            </div>
            <div class="row">
                
                <div class="col-sm-4">
                    <h4>Router</h4>
                    <div class="menu-delete-grap router mt-5 p-4">
                        <?php foreach($rs['router'] as $k=>$v):?>
                        <a href="<?=$k;?>" class=""><!--<i class="fa fa-long-arrow-right " aria-hidden="true"></i> &#8259; &#8669;&#8872; -->&#8887;</a><?=$k;?> &nbsp;
                        <a href="javascript:void(0)" onclick="$('#id').val(0);$('#new_id').val(0);$('#parent_id').val(1);$('#display').val('');$('#router').val('<?=$k;?>'); $('#sitemin_menu_model').modal(); return false;" >
                            <i class="fa fa-plus-square-o" aria-hidden="true" style="color:#269abc;"></i>
                        </a>
                        <br>
                        <div class="router-m"></div>
                        <?php endforeach;?>
                    </div>
                </div>
                <div class="col-sm-8"><?=$menutree_html;?></div>

            </div>
        </div>
    </div>
</div>

<script>
function order_area_show(ev, e){
	ev.preventDefault();
		e.style.height="24px";
		e.style.background="#ccc";
}
function order_area_hide(e){
		e.style.height="3px";
		e.style.background="transparent";
}

function order_save(ev, e){
	ev.preventDefault();
	ev.stopPropagation();
	var id = $('#id').val();
	var d = e.id.split('_')
	var parent_id = d[1];
	var order = d[2];
	common.mask.up();
	$.ajax({
		url: '/sitemin/acl/menutree/item_move_2',
		type: 'post',
		dataType: 'json',
		data: {id:id, parent_id:parent_id, order:order, _token:$('#_token').val()},
		success: function(data) {
			if(data.status =='success'){
				location.reload();
			}else{
		 		alert(data.msg)
				common.mask.down();
		        }
		}
	});
}

function allowDrop(ev,e) {
	ev.preventDefault();
	e.style.background="#ccc";
	e.style.padding="5px";
}
function allowDrop_hide(e) {
	e.style.background="transparent";
    	e.style.padding="0px";
}

function drag(ev, el) {
	$('#id').val(el.id.match(/\d+/));
	//ev.dataTransfer.setData("text", ev.target.id);
}

function drop(ev, el) {
	ev.preventDefault();
	ev.stopPropagation();
	$('#new_id').val(el.id.match(/\d+/));
	common.mask.up();
	$.ajax({
		url: '/sitemin/acl/menutree/item_move_1',
		type: 'post',
		dataType: 'json',
		data: $('form#menu_item').serialize(),
		success: function(data) {
			if(data.status =='success'){
				location.reload();
			}else{
		 		alert(data.msg)
				common.mask.down();
		        }
		}
	});

}

function menu_item_save(){
	common.mask.up();
	$.ajax({
		url: '/sitemin/acl/menutree/item_save',
		type: 'post',
		dataType: 'json',
		data: $('form#menu_item').serialize(),
		success: function(data) {
			if(data.status =='success'){
				location.reload();
			}else{
		 		$('#menu_item .msg').html(data.msg.join(', '))
				common.mask.down();
		        }
		}
	});
}
function menu_item_delete(id){
	common.mask.up();
	$.ajax({
		url: '/sitemin/acl/menutree/item_delete',
		type: 'post',
		dataType: 'json',
		data: {id:id, _token:$('#_token').val()},	//token save in the model form when page is load
		success: function(data) {
			if(data.status =='success'){
				location.reload();
			}else{
		 		alert(data.msg.join(', '))
				common.mask.down();
		        }
		}
	});
}

$(function() {

	//clean root element
	$('.menu-root > ul > li >a + a').remove();
	$('.menu-root > ul > li >a + a').remove();
	$('.menu-root > ul > li > a + span').html($('.menu-root > ul > li > a +span > strong'));

	//resize rooter
	$('.router').height($('.tree').height());

	function split( val ) {
			return val.split( /,\s*/ );
	}
	function extractLast( term ) {
		return split( term ).pop();
	}

	$( "#router" ).each(function(){
		$(this).autocomplete({
			source: "/sitemin/acl/router/search",
			minLength: 2,
			select: function( event, ui ) { }
		});
	})

});


</script>

<!-- Modal -->
<div class="modal fade" id="sitemin_menu_model" role="dialog">
	<div class="modal-dialog">
		<!-- Modal content-->
		<div class="modal-content px-5 mt-7">
			<div class="modal-header">
				<h4 class="modal-title">Menu Item</h4>
			</div>
			<form id="menu_item" >
				<p class="msg"></p>
				<input name="id" id="id" value="" type="hidden">
				<input name="parent_id" id="parent_id" value="" type="hidden">
				<input name="_token" id="_token" value="<?=$rs['_token'];?>" type="hidden">
				<input name="new_id" id="new_id" value="" type="hidden">
				<div class="form-group">
					<label for="display">Display:</label>
					<input type="text" name="display" class="form-control" id="display">
				</div>
				<div class="form-group" style="position:relative;">
					<label for="router">URL:</label>
					<input name="router" class="form-control" id="router">
				</div>
<!--				<div class="form-group">
					<label for="role">Roles:</label>
					<input name="role" class="form-control" id="role">
				</div>
-->

			</form>
			<div class="modal-footer">

				<button type="button" class="btn btn-warning" onclick="menu_item_save()">Save</button>
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
			</div>
		</div>
	</div>
</div>
