
<div class="container my-5">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3 white-container">
            <h3 class="mx-auto mb-5 text-uppercase">User role update</h3>
            <?php if($rs['_msg'] ):?>
	        <h4 class="alert alert-danger"><?=$rs['_msg'];?></h4>
	        <?php endif;?>
             <form  action="?id=<?=$rs['id']; ?>"  method="POST" id="filter">
    <!-- 	        <input type="hidden" name="id" value="<?=$rs['id']; ?>" />-->
 	            <input type="hidden" name="_token" value="<?=$rs['_token']; ?>" />
 	            
                    <div class="form-group row">
	                  <label class="form-control-label col-sm-3" for="name">Name:</label>
	                  <div class="col-sm-9">
		                <input type="text" class="form-control" name="name" value="<?=$rs['name']; ?>">
	                  </div>
                    </div>
                    <div class="form-group row">
	                  <label class="form-control-label col-sm-3" for="description">Description:</label>
	                  <div class="col-sm-9">
		                <input type="text" class="form-control" name="description" value="<?=$rs['description']; ?>">
	                  </div>
                    </div> 
                 
                 <div class="form-group">        
                  <div class="d-flex justify-content-center mt-5">
                    <input type="submit" class="btn btn-warning  mr-4" name="save"  value="<?php echo $rs['id'] ?  "&#10003 Update" : "&#10003 Create"; ?>" />
                    <div class="btn btn-light ">
		            <a href="/sitemin/acl/role"><span class="fa fa-arrow-left"> Back</a>
                    </div>
                  </div>      
                </div>
              </form>
       </div>
   </div> 
</div>
<hr>  
<script>
  	
$(function() {
	

    function split( val ) {
      return val.split( /,\s*/ );
    }
    function extractLast( term ) {
      return split( term ).pop();
    }
 
    $( "#userrole" )
      // don't navigate away from the field on tab when selecting an item
      .bind( "keydown", function( event ) {
        if ( event.keyCode === $.ui.keyCode.TAB &&
            $( this ).autocomplete( "instance" ).menu.active ) {
          event.preventDefault();
        }
      })
      .autocomplete({
        source: function( request, response ) {
          $.getJSON( "/sitemin/acl/search/role", {
            term: extractLast( request.term )
          }, response );
        },
        search: function() {
          // custom minLength
          var term = extractLast( this.value );
          if ( term.length < 2 ) {
            return false;
          }
        },
        focus: function() {
          // prevent value inserted on focus
          return false;
        },
        select: function( event, ui ) {
          var terms = split( this.value );
          // remove the current input
          terms.pop();
          // add the selected item
          terms.push( ui.item.value );
          // add placeholder to get the comma-and-space at the end
          terms.push( "" );
          this.value = terms.join( ", " );
          return false;
        }
      });
      
      
});


</script>
