<?php
//_dv($rs);
?>
<div class="container my-5">
<div class="row">
   <div class="col-12 col-md-6 offset-md-3 white-container">
        <h3 class="mx-auto mb-5 text-uppercase">API User update</h3>
        <?php if($rs['_msg'] ):?>
	    <h4 class="alert alert-danger"><?=$rs['_msg'];?></h4>
	<?php endif;?>
	    <form  action=""  method="POST" id="filter">
 	        <input type="hidden" name="id" id="id" value="<?=$rs['id']; ?>" />
 	        <input type="hidden" name="_token" id="_token" value="<?=$rs['_token']; ?>" />

                <div class="form-group row">
	              <label class="form-control-label col-sm-3" for="login_id">Login ID</label>
	              <div class="col-sm-9 input-group">
		            <input type="text" class="form-control" name="login_id" id="login_id" value="<?=$rs['login_id']; ?>">
					<span></span>
	              </div>
                </div>
                <div class="form-group row">
	              <label class="form-control-label col-sm-3" for="detail">Detail:</label>
	              <div class="col-sm-9">
		             <textarea rows="4" class="width100"  name="detail" id="detail" ><?=strip_tags($rs['detail']);?></textarea>
	              </div>
                </div>

                <div class="form-group row">
	              <label class="form-control-label col-sm-3" for="quota">Quota</label>
	              <div class="col-sm-9">
		            <input type="text" class="form-control" name="quota" id="quota" value="<?=$rs['quota']; ?>">
	              </div>
                </div>
                <div class="form-group row">
	              <label class="form-control-label col-sm-3" for="quota_period_seconds">Quota Length</label>
	              <div class="col-sm-9">
		            <select class="form-control" name="quota_period_seconds" id="quota_period_seconds" >
		            	<option value="86400" <?=($rs['quota_period_seconds'] == '86400') ? 'selected="true"' :'';?> >1 day</option>
		            	<option value="604800" <?=($rs['quota_period_seconds'] == '604800') ? 'selected="true"' :'';?> >1 week</option>
		            	<option value="1209600" <?=($rs['quota_period_seconds'] == '1209600') ? 'selected="true"' :'';?> >2 weeks</option>
		            	<option value="2592000" <?=($rs['quota_period_seconds'] == '2592000') ? 'selected="true"' :'';?> >30 days</option>
		            	<option value="7776000" <?=($rs['quota_period_seconds'] == '7776000') ? 'selected="true"' :'';?> >90 days</option>
		            	<option value="15552000" <?=($rs['quota_period_seconds'] == '15552000') ? 'selected="true"' :'';?> >180 days</option>
		            	<option value="31536000" <?=($rs['quota_period_seconds'] == '31536000') ? 'selected="true"' :'';?> >1 year</option>
		            </select>
	              </div>
                </div>

                <div class="form-group row">
	              <label class="form-control-label col-sm-3" for="quota_start_seconds">Quota Start</label>
	              <div class="col-sm-9">
		            <input type="text" class="form-control" name="quota_start_seconds" id="quota_start_seconds" value="<?=$rs['quota_start_seconds'] ? date("Y-m-d", $rs['quota_start_seconds']) : date("Y-m-d");?>">
	              </div>
                </div>
      <script>
	$( function() {
		$( "#quota_start_seconds" ).datepicker({ dateFormat: "yy-mm-dd"});
	} );
  </script>
                <div class="form-group row">
	              <label class="form-control-label col-sm-3" for="quota_counter">Quota Counter</label>
	              <div class="col-sm-9">
		            <input type="text" class="form-control" name="quota_counter" id="quota_counter" value="<?=$rs['quota_counter']; ?>">
	              </div>
                </div>
                 <div class="form-group row">
	              <label class="form-control-label col-sm-3" for="status">Status</label>
	              <div class="col-sm-9">
	              		<select name="status" id="status">
	              		<?php foreach ($rs['status_options'] as $k=>$v):?>
	              			<option value="<?=$v;?>" <?=($v == $rs['status']) ? 'selected="true"' : '';?>><?=$v;?></option>

	              		<?php endforeach;?>
	              		</select>
	              </div>
                </div>
             <div class="form-group">
              <div class="d-flex justify-content-center mt-5">
                <input type="submit" class="btn btn-warning mr-4" name="save" id="save" value="<?php echo $rs['id'] ?  "&#10003 Update" : "&#10003 Create"; ?>" />
                <div class="btn btn-light">
		        <a href="<?=$rs['_return'];?>"><span class="fa fa-arrow-left"> Back</a>
                </div>
              </div>
            </div>
          </form>
    </div>
    </div>
</div>
<hr>

<script>

$(function() {

	$('#login_id').blur(function(){

			$.ajax({
				url: '/api/user/idcheck',
				data: {id:$('#id').val(),'login_id':$('#login_id').val(),_token:$('#_token').val()},
				success: function(data){
						if (data == 'ok') {
                            $('#save').prop('disabled', false);
							$('#login_id').next().html('<i class="fa fa-check" aria-hidden="true"></i>');
                        }else{
                            $('#save').prop('disabled', true);
							$('#login_id').next().html('<i class="fa fa-times aria-hidden="true"></i>');
						}
				}
			});

	})


});

</script>
