<?php
/**
 * perpare data
 */
?>
<style type="text/css">
.h-divider{
 margin-top:5px;
 margin-bottom:5px;
 height:1px;
 border-top:1px solid gray;
}
</style>
<div class = "container">
	<div class="row px-3">
		<div class="mt-5 the-title">
			<h3>API --  <span class = "small">List of API and methods</span>  </h3>
		</div>
	</div>
	<?php foreach ($rs['api'] as $ka=>$va):?>
   
	<div class="row">
		
		<div class="col-sm-3 col-xs-4 alert-secondary py-2"><div class="well well-sm"><i><?=_X_URL;?></i><?=preg_replace('/^\_/', '', $va['L']);?></div></div>
        <div class="col-sm-1 col-xs-1 "></div>
		<div class="col-sm-8 col-xs-7  alert-secondary text-center  py-2"><pre><b><?=$va['desc'];?></b></pre></div>
    </div>
     <div class="h-divider row"></div>
   
		<?php foreach ($va['method'] as $km=>$vm):?>
         <div class="row">
			<div class="col-sm-3 col-xs-4 text-center">/<b><?=$vm['name'];?></b></div>
              <div class="col-sm-1 col-xs-1 "></div>
			<div class="col-sm-8 col-xs-7 text-center"><pre><?=preg_replace('/\n\t/ims', "\n", $vm['desc']);?></pre></div>
            
        </div>
      
     
		<?php endforeach;?>
        
	
	<?php endforeach;?>

	
	<!-- bottom -->
	<div class="row">
		<div class="h-divider col-sm-12"></div>
		<div class="col-sm-3 col-xs-4 alert alert-secondary"><h5 class="well well-sm"></h5></div>
		<div class="col-sm-9 col-xs-8 align-text-top  alert alert-secondary"><pre><b></b></pre></div>
			<div class="h-divider col-sm-12"></div>
			<div class="col-sm-2 col-xs-hidden"></div>
			<div class="col-sm-2 col-xs-2"></div>
			<div class="col-sm-8 col-xs-10 align-text-top"><pre></pre></div>
	</div>
</div>
