<?php

?>

<script>
var _token = '<?=$rs['token'];?>';
</script>

<?php include _X_LAYOUT . '/sitemin/include_vue.phtml'; ?>

<div class="container-fluid mb-5">
	<div :class="'row '+t_hide" id="fifthTable">
		<div class="col-sm-12">
			<h3 class=" mt-5 h3bottom">Profile</h3>
			<div >
				<table class="table table-striped">
					<tr>
						<th v-for="col in columns" :class="'c--'+col">{{col}}</th>
					</tr>
					<tr v-for="row in get_rows()">
						<td valign="top" v-for="col in columns"  :class="'c--'+col">{{row[col]}}</td>
					</tr>
				</table>
			</div>
		</div>
		<script>
		var fifthTable = new Vue({
			el: '#fifthTable',
			data: {
				quotes: '',
				rows :  $.ajax({
						url: '/sitemin/user/profile?cmd=brief',
						method: 'POST',
						dataType: 'json',
						async: false
					}).responseJSON
				},
			methods: {
				"get_rows": function () {return this.rows; }
			},
			computed: {
				"columns": function columns() {
						if (!this.rows || this.rows.length == 0) return [];
						return Object.keys(this.rows[0])
					},
				"t_hide":function(){
						return (!this.rows || this.rows.length == 0) ? 'Hide' : 'Yes';
					}
			}
		});
		</script>
	</div>
    <hr>
	<div class="my-2" id="sixthTable">
	  <div :class="'row '+t_hide">
        <div class="col-lg-7">
            <h3 class="t_hide h3bottom">Message Board</h3>
			<div class="t_hide">
				<table class="table table-striped table-hover">
					<tr>
						<!-- <th v-for="col in columns" v-on:click="sortTable(col)" :class="'c--'+col">{{col}}
						<div class="arrow" v-if="col == sortColumn" v-bind:class="[ascending ? 'arrow_up' : 'arrow_down']"></div>
						</th> -->
						<th v-on:click="sortTable('From')">[From]
							<div class="arrow"  v-if=" 'From' == sortColumn" v-bind:class="[ascending ? 'arrow_up' : 'arrow_down']"></div>
						</th>
						<th  v-on:click="sortTable('Message')">
							[Message]
							<div class="arrow"  v-if=" 'Message' == sortColumn" v-bind:class="[ascending ? 'arrow_up' : 'arrow_down']"></div>
						</th>
							<th v-on:click="sortTable('Date')">
							[Date]
							<div class="arrow" v-if="'Date' == sortColumn" v-bind:class="[ascending ? 'arrow_up' : 'arrow_down']"></div>
						</th>
						<th></th>
					</tr>
					<tr v-for="row in get_rows()" >
						<td>{{row.From}}</td>
						<td>{{row.Message}}</td>
						<td>{{row.Date}}</td>
						<!-- <td valign="top"  v-for="col in columns" :class="'view-'+row.viewed + ' c--'+col"><pre>{{row[col]}}</pre> </td> -->
						<td> <a class="btn btn-extra-small btn-rounded btn-light-border" href="javascript:void(0)" v-on:click="message_remove(row.id)"> <i class="fa fa-trash-o" aria-hidden="true"></i></a></td>
					</tr>
				</table>
				<ul class="navbar-nav ml-auto pagination0">
					<li v-for="i in num_pages()" v-bind:class="[i == currentPage ? 'page-item number active' : 'page-item number']" ><a class="page-link" href="javascript:void(0);"  v-on:click="change_page(i)">{{i}}</a></li>
				</div>
			</div>

<!--
        <div class="col-lg-6">
            <div >
                <h3>Last24:</h3>
                <div class="last24">
                    <div id="last24-placeholder" class="lase24-placeholder" style="float:left; width:375px;height:300px"></div>
                </div>
            </div>
        </div>
-->
<!--
        <div class="col-lg-3">
            <div >
                <h3>Users : </h3>
                {{users}}
            </div>
        </div>

		<div class="col-lg-3">
			<div >
				<h3>Users : </h3>
				{{users}}
			</div>
		</div>
		<div class="col-lg-3">
			<div >
				<h3>Login in last 24h : </h3>
				{{login24}}
			</div>
		</div>
-->
		<div class="col-lg-4">
	        <div >
	            <h3 class="top10-title Hide h3bottom">Top 10 Url in last 24h :</h3>
	            <ul class="top10title">
	                <li v-for="url in top10url"> {{url.router}} <span class="badge badge-light">{{url.c}}</span></li>
	            </ul>
	        </div>
	    </div>
      </div>
      <hr>
      <div class="container">
		  <div class="d-flex justify-content-center">
	            <div >
	                <h3  class="top5-title Hide h3bottom">Top 5 Url last 30 days:</h3>
                    <div class="demo-container">
                        <div id="placeholder" class="demo-placeholder" style="float:left; width:675px;height:240px"></div>
			<p id="choices" style="float:left; width:235px;"></p>
                    </div>
	            </div>
	    </div>
      </div>
        <script src="/package/jquery/jquery.flot.js" ></script>
		<script>
		var sixthTable = new Vue({
			el: '#sixthTable',
			data: {
				currentPage: 1,
				elementsPerPage: 12,
				ascending: false,
				sortColumn: '',
				users :  0,
				login24: 0,
				top10url: [],
				last24: [],
				top5url: [],
				rows :  $.ajax({
						url: '/sitemin/user/message?cmd=list',
						method: 'POST',
						dataType: 'json',
						async: false
					}).responseJSON || []
				},
			methods: {
				"sortTable": function (col) {
						if (this.sortColumn === col) {
							this.ascending = !this.ascending;
						} else {
							this.ascending = true;
							this.sortColumn = col;
						}

						var ascending = this.ascending;

						this.rows.sort(function(a, b) {
							if (a[col] > b[col]) {
								return ascending ? 1 : -1
							} else if (a[col] < b[col]) {
								return ascending ? -1 : 1
							}
							return 0;
						})
					},
				"message_remove":	function(id){
						$.ajax({
							url: '/sitemin/user/message?cmd=delete&id='+id,
							success: function(data){ }
						});
					 	var nrows = [];
					 	for(var i in this.rows){
					 		if(this.rows[i].id == id) this.rows.splice(i,1);

					 	}
					},
				"num_pages": function () {
						return Math.ceil(this.rows.length / this.elementsPerPage);
					},
				"get_rows": function () {
						//if(!this.rows || this.rows.length == 0 ) return []
						var start = (this.currentPage-1) * this.elementsPerPage;
						var end = start + this.elementsPerPage;
						return this.rows.slice(start, end);
					},
				"change_page": function (page) {
					this.currentPage = page;
				}
			},
			computed: {
				"columns": function columns() {
					if (!this.rows || this.rows.length == 0) return [];
					return Object.keys(this.rows[0])
				},
				"t_hide":function(){
					return (!this.rows || this.rows.length == 0) ? 'Hide' : 'Yes';
				}
			},
			mounted: function () {
                /*
				$.ajax({ url: '/sitemin/status?cmd=users&_token='+_token,
					success: function(ret){
						sixthTable.users = parseInt(0+ret);
					}
				});
				$.ajax({ url: '/sitemin/status?cmd=login24&_token='+_token,
					success: function(ret){
						sixthTable.login24 = parseInt(0+ret);
					}
				});*/
				$.ajax({ url: '/sitemin/status?cmd=top10url&_token='+_token, dataType:'json',
					success: function(ret){
						$('.top10-title').show();
						sixthTable.top10url = ret;
					}
				});
		                // $.ajax({ url: '/sitemin/status?cmd=last24&_token='+_token, dataType:'json',
		                //     success: function(ret){
		                //         sixthTable.last24 = ret;
				// 	ret =  [ ["January", 10], ["February", 8], ["March", 4], ["April", 13], ["May", 17], ["June", 9] ];
		                //         var options =  {
				// 			series: {
				// 				bars: {
				// 					show: true,
				// 					barWidth: 0.6,
				// 					align: "center"
				// 				}
				// 			},
				// 			xaxis: {
				// 				mode: "categories",
				// 				tickLength: 0
				// 			}
				// 		};
				//
		                //             $.plot("#last24-placeholder", ret, options);
		                //     }
		                // });
				$.ajax({ url: '/sitemin/status?cmd=top5url&_token='+_token, dataType:'json',
					success: function(ret){
						$('.top5-title').show();
						sixthTable.top5url = ret;
                        			var datasets = ret;
						var i = 0;
						$.each(datasets, function(key, val) {
							val.color = i;
							++i;
						});
						// insert checkboxes
						var choiceContainer = $("#choices");
						$.each(datasets, function(key, val) {
							choiceContainer.append("<br/><input type='checkbox' name='" + key +
								"' checked='checked' id='id" + key + "'></input>" +
								"<label for='id" + key + "'>"
								+ val.label + "</label>");
						});
						choiceContainer.find("input").click(plotAccordingToChoices);

						function plotAccordingToChoices() {
							var data = [];
							choiceContainer.find("input:checked").each(function () {
								var key = $(this).attr("name");
								if (key && datasets[key]) {
									data.push(datasets[key]);
								}
							});
							if (data.length > 0) {
								$.plot("#placeholder", data, {
									yaxis: {
										min: 0
									},
									xaxis: {
										tickDecimals: 0
									}
								});
							}
						}
						plotAccordingToChoices();
					}
				});
		        }
		});

		</script>
	</div>
</div>
<hr>