<?php
$captcha = !$rs['no_captcha'];
?>
<script src='https://www.google.com/recaptcha/api.js'></script>


<div class=" login-page container mt-7">
	<div class="row justify-content-center">
		<div class="login-page">
			<div class="login-logo">
				<div class="title">
					<h3 class="mt-4">RESET MY PASSWORD</h3>
					<h4><?=$rs['user']['username'];?>&lt; <?=$rs['user']['email'];?> &gt;</h4>
				</div>
			</div>

				<form method="post" role="form" class="form-horizontal" id="login-form" onsubmit="return reset_password(this);">
					<input type="hidden" name="ret" id="ret" value="/sitemin/dashboard" />
					<input type="hidden" name="hash" id="hash" value="<?=$rs['hash'];?>" />
					<input type="hidden" name="save" id="save" value="1" />


					<div class="input-group mb-3 form-group mt-4">
					<input type="password" class="form-control input-lg" id="p1"  name="p1" required="" placeholder="Password( >= 8 chars) "  pattern=".{8,}" >
					</div>
							<br/>
					<div class="input-group mb-3 form-group">
					<input type="password" class="form-control input-lg" id="p2"  name="p2" required="" placeholder="Password( >= 8 chars)"  pattern=".{8,}">
					</div>
					<br/>

					<?php if($captcha): ?>
						<script src="https://www.google.com/recaptcha/api.js" async defer></script>
						<script>
						function onSubmit(token) {
							$("#login-form").submit();
						}
						</script>
						<button type="button" value="1" name="go" data-sitekey="<?=$rs['google_key'];?>" data-callback='onSubmit' class="g-recaptcha btn btn-lg text-center btn-secondary btn-block " id="save">Login</button>
					<?php else: ?>
						<button type="submit" value="1" name="go" id="save">Save</button>
					<?php endif; ?>
                    			<br/>
				</form>

		</div>
	</div>
</div>
<div class="visibilityHidden">
	<form method="post" atcion="?" id="rform" target=''>
<!--		<input type="hidden" name="formAction" value="submit" />
		<input type="hidden" name="ifhPage" value="ifhPage" />
		<input type="hidden" name="lastSubmitter" value="undefined" />
		<input type="hidden" name="submittedBy" value="undefined" />
-->		<input type="text" name="password" value="" id="rpassword" />
		<input type="text" name="userName" value="" id="rusername" />
	</form>
</div>


<script>

(function($){
	// $('ul.sidebar-nav').html('');
	// $('ul.navbar-nav').html('');
})(jQuery)



function reset_password(form){

	var p1 = $('#p1').val()
	var p2 = $('#p2').val()
	if(p1 != p2) {
		alert("Password miss match");
		return false;
	}
	common.mask.up()
	//$('.alert').attr('class', 'alert').html('<img src="<?=_X_URL?>/media/image/ajax-loader.gif" />');
	$.ajax({url: "", data:$(form).serialize(),type:'post',
		success: function(){
			$('.login-page').html('<h3>New Password saved</h3><h4> </h4><button onclick="window.location=\'/sitemin/login\'">Try Login</button>');
			common.mask.down()
		}
	});

	return false;
}

</script>
