<?php
/**
 * perpare data
 */

?>

    <div class="row mb-5">
        <div class="col-12 col-md-10 offset-md-1">    
            <form id="filter" class="search-form" method="get"  >
	            <div class="row mt-5">
		            <div class="the-title">
			            <h3 class="text-uppercase">Users -- <span class = "small">List of users</span>  </h3>
		            </div>
	            </div>
	            <br>
	            <div class="total-row row mt-2 mr-3"><!-- total start -->
		            <div class="col-sm-2 ">Total: <span><?=count($rs['data']);?></span></div>
                    <div class="col-sm-2 form-group has-icon">
                        <input name="currentpage" type="hidden" id="page" value="<?=$rs['page']['no']?>" />
                        <input name="sort" type="hidden"  id="sort" value="<?=$rs['sort']?>" />

                        <label class="sr-only" for="username">Username</label>
                        <span class="fa fa-user form-control-feedback"></span>
                        <input type="text" class="form-control" id="username" name="filter[username]" placeholder="Username" value="<?=$rs['filter']['username'];?>">
                    </div>
		            
                    <div class="col-sm-2 form-group has-icon">
                        <label class="sr-only" for="email">Email</label>
                        <span class="fa fa-envelope form-control-feedback"></span>
                        <input type="text" class="form-control" id="email" name="filter[email]" placeholder="Email" value="<?=$rs['filter']['email'];?>">
                    </div>        
                    <div class="col-sm-2 ">
                        <button class="btn btn-extra-small btn-rounded btn-light-border" type="submit" >
                            <span class="fa fa-search">Search</span>
                        </button>
                    </div>                       
	            </div>
            </form>

	        <script>

	        function TheSort(sort){
		        var current_sort = jQuery('#sort');
		        if(current_sort.val() == sort) current_sort.val('-'+sort);
		        else current_sort.val(sort);
		        jQuery('#filter')[0].submit();
	        }

	        </script>



	        <!-- grid table -->
	        <div class="row">
		        <table class="table table-striped table-hover">
			        <tr>
				        <th class=".Hide">
					        ID
				        </th>
				        <th>
					        <a href="javascript:void(0)" onclick="TheSort('username')">User Name &nbsp;<i class="fa  <?=preg_match('/^.?username$/',$rs['sort'])? (preg_match('/^\-/',$rs['sort'])?'fa-sort-amount-desc':'fa-sort-amount-asc') :'fa-task';?>"></i></a>
				        </th>
				        <th>
					        <a href="javascript:void(0)" onclick="TheSort('email')">Email &nbsp;<i class="fa  <?=preg_match('/^.?email$/',$rs['sort'])? (preg_match('/^\-/',$rs['sort'])?'fa-sort-amount-desc':'fa-sort-amount-asc') :'fa-task';?> "></i></a>
				        </th>

				        <th>
					        User Role
        <!--					<a href="javascript:void(0)" onclick="TheSort('userrole')">User Role &nbsp;<i class="fa  <?=preg_match('/^.?userrole$/',$rs['sort'])? (preg_match('/^\-/',$rs['sort'])?'fa-sort-amount-desc':'fa-sort-amount-asc') :'fa-task';?>"></i></a>-->
				        </th>
				        <th>
					        <a href="javascript:void(0)" onclick="TheSort('status')">Status &nbsp;<i class="fa  <?=preg_match('/^.?status$/',$rs['sort'])? (preg_match('/^\-/',$rs['sort'])?'fa-sort-amount-desc':'fa-sort-amount-asc') :'fa-task';?>"></i></a>
				        </th>
				        <th>
					        <a href="javascript:void(0)" onclick="TheSort('created')">Created &nbsp;<i class="fa  <?=preg_match('/^.?created$/',$rs['sort'])? (preg_match('/^\-/',$rs['sort'])?'fa-sort-amount-desc':'fa-sort-amount-asc') :'fa-task';?>"></i></a>
				        </th>
				        <th>Action <a class="btn btn-extra-small btn-rounded btn-light-border" href="/sitemin/user/edit" class="" role="button"><span  class="fa fa-plus"></a></th>
			        </tr>
		        <?php
		        foreach ($rs['data'] as $k=>$r): ?>
			        <tr class="<?php echo $k%2 ? 'even' : 'odd'; ?>">
				        <td class=".Hide"><?=$r['id']?></td>
				        <td><?=$r['username'];?></td>
				        <td><?=$r['email'];?></td>
				        <td><?=$r['userrole'];?></td>
				        <td><?=$r['status'];?></td>
				        <td><?=$r['created'];?></td>
				        <td>
					        <a class="btn btn-extra-small btn-rounded btn-light-border"  href="javascript:void(0)" onclick="showmodal(<?php echo $r['id']; ?>)"><span class="fa fa-gear"> PWD</span></a>
					        <a class="btn btn-extra-small btn-rounded btn-light-border" role="button" href="/sitemin/user/edit/?id=<?=$r['id']?>" ><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
        <!--					<a class="btn btn-sm btn-info"  id="delete-<?=$r['id']?>" href="/sitemin/user/delete/?id=<?=$r['id']?>&_token=<?=$rs['_token'];?>" ><i class="fa fa-trash"></i></a>-->
					        <a class="btn btn-extra-small btn-rounded btn-light-border" href="/sitemin/user/<?php echo $r['status'] == 'active' ? 'suspend' : 'active'; ?>?id=<?=$r['id']?>&_token=<?=$rs['_token'];?>"><span class="fa fa<?php echo $r['status'] == 'active' ? '-pause' : 'fa  fa-play'; ?>"> <?php echo $r['status'] == 'active' ? 'Stop' : 'Active'; ?></span></a>
				        </td>
			        </tr>
		        <?php endforeach; ?>
		        </table>
	        </div>

	        <!-- pagination -->
            <div class="row mt-1">
	            <?php include _X_LAYOUT.'/sitemin/pagination.phtml';?>
	            
            </div>
        </div>
    </div>

<hr>

<!-- Modal -->
<div class="modal fade mt-5" id="myModal" role="dialog">
	<div class="modal-dialog">
		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header" style="padding:15px 20px;">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				
			</div>
            <h4 class="px-5">Please input new password</h4>
			<div class="modal-body" style="padding:20px 50px;">
				<form role="form" class="modal_form">
					<input name="id" class="v_id" type="hidden" />
			 	        <input type="hidden" name="_token" class="v_token" value="<?=$rs['_token']; ?>" />

					<div class="form-group">
						<label for="comment">New Password</label>
						<input type="password" class="form-control v_password" id="comment" placeholder="Enter new password" name="password" value="pwd">
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button  class="btn btn-warning" data-dismiss="modal" onclick="savepassword()"><span class="glyphicon glyphicon-ok"></span> Save</button>
				<button  class="btn btn-light " data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
			</div>
		</div>
		<!-- Modal content-->
	</div>
</div>
<!-- Modal -->

<script>
function showmodal(id){
	$('.v_id').val(id)
	$('#myModal').modal('show');
}

function savepassword(){

		$.ajax({
		  url: '/sitemin/user/password',
		  data: {id:$('.v_id').val(),'n2048':$('.v_password').val(),_token:$('.v_token').val()},
		  success: function(data){
		  }
		});
}


$(function() {

	$( "#username" ).each(function(){
		$(this).autocomplete({
			source: "/sitemin/user/search/name",
			minLength: 2,
			select: function( event, ui ) { }
		});
	})
	$( "#email" ).each(function(){
		$(this).autocomplete({
			source: "/sitemin/user/search/email",
			minLength: 2,
			select: function( event, ui ) { }
		});
	})

});
</script>
